### ISSUE TITLE
ocurrence() não está puxando dados completos de ocorrência

### ISSUE THREAD

**Issue by ggrittz** [gustavobio/flora#10]
Olá,

Estou usando o flora para checar uma lista de espécies que possuo para SC, RS, e PR, se ocorrem ou não na Flora do Brasil. Todavia, a função occurrence() não está retornando algumas ocorrências conhecidas para os estados. Por exemplo, Aiouea glaziovii ocorre em SC, PR, ES, RJ e SP (ver img) mas apenas retorna RJ na função. O que pode estar ocorrendo?

Segue abaixo um simples teste.

teste <- occurrence(states = c('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 
                         'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 
                         'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 
                         'RO', 'RR', 'SC', 'SP', 'SE', 'TO'), type = 'any', taxa = 'Aiouea glaziovii')
print(teste)
      id    family       search.str occurrence
1 607775 Lauraceae Aiouea glaziovii      BR-RJ

Agradeço desde já. 

![image](https://user-images.githubusercontent.com/45982618/107554995-6accee80-6bb5-11eb-9a9b-2a83d5e4c5db.png)

**Comment by gustavobio** [comment]
@ggrittz, que versão do pacote você tem instalada? Aqui aparece o resultado esperado:

![Screenshot 2021-04-08 175808](https://user-images.githubusercontent.com/30267/114095705-2186db80-9894-11eb-8fd1-88e27e9f13a5.jpg)

**Comment by ggrittz** [comment]
> @ggrittz, que versão do pacote você tem instalada? Aqui aparece o resultado esperado:
> 
> ![Screenshot 2021-04-08 175808](https://user-images.githubusercontent.com/30267/114095705-2186db80-9894-11eb-8fd1-88e27e9f13a5.jpg)

Opa, 0.3.4. Desatualizada?

**Comment by gustavobio** [comment]
A versão do CRAN está bem desatualizada. Há um limite de 5Mb e com as atualizações recentes da flora o banco ficou maior, então não tenho como atualizar lá. Tente pelo github:

install.packages("devtools")
devtools::install_github("gustavobio/flora")

**Comment by ggrittz** [comment]
> A versão do CRAN está bem desatualizada. Há um limite de 5Mb e com as atualizações recentes da flora o banco ficou maior, então não tenho como atualizar lá. Tente pelo github:
> 
> install.packages("devtools")
> devtools::install_github("gustavobio/flora")

Ah, vacilo meu, então. Vou tentar, valeu!
