### ISSUE TITLE
Não consigo achar algumas espécies que estão no BD do site

### ISSUE THREAD

**Issue by ricardopmarinho** [gustavobio/flora#11]
Quando pesquiso algumas espécies no pacote R pelo get.taxa, o resultado vem como não encontrado, apesar de a espécie constar no site.

Um exemplo é Aloe vera. No site eu consigo as informações, mas no pacote, o retorno é NA

A pesquisa pelo gênero "Eucalyptus" também acontece isso

A pesquisa no site foi por este link

http://floradobrasil.jbrj.gov.br/reflora/listaBrasil/ConsultaPublicaUC/ConsultaPublicaUC.do#CondicaoTaxonCP

**Comment by ricardopmarinho** [comment]
A pesquisa no site foi por este link

http://floradobrasil.jbrj.gov.br/reflora/listaBrasil/ConsultaPublicaUC/ConsultaPublicaUC.do#CondicaoTaxonCP

**Comment by gustavobio** [comment]
Se puder cole exatamente o código que você usou e versão. Aqui, na última versão, os dois taxons mencionados aparecem:

![Screenshot 2021-04-08 175346](https://user-images.githubusercontent.com/30267/114095339-ad4c3800-9893-11eb-8875-297c508a02fc.jpg)

**Comment by ricardopmarinho** [comment]
![image](https://user-images.githubusercontent.com/1401437/114096177-bee20f80-9894-11eb-8fee-f6b8146b3693.png)

para Eucalyptus deu a mesma coisa

**Comment by gustavobio** [comment]
Tenta instalar aqui pelo github:

require(devtools)
install_github("gustavobio/flora")

**Comment by ricardopmarinho** [comment]
Funcionou, obrigado
