### ISSUE TITLE
Search using ID?

### ISSUE THREAD

**Issue by jaum20** [gustavobio/flora#14]
is there a way to get the data using the ID instead of plant names?

**Comment by gustavobio** [comment]
Hi @jaum20 

There isn't a function to do so, but this could be easily achieved with a workaround:

```R
library(flora)
library(dplyr)

flora:::all.taxa %>%
  filter(id %in% c(606070, 139067, 109768))
```

You can then use ```get.taxa()``` to fix synonyms if needed.

**Comment by jaum20** [comment]
Thank you
