### ISSUE TITLE
Are the data up to date?

### ISSUE THREAD

**Issue by jaum20** [gustavobio/flora#15]
Looks like occurrence data are no up to date. For example, for the species 'Bixa arborea'

```
get.taxa('Bixa arborea',states = TRUE)
    id    scientific.name accepted.name   family taxon.rank taxon.status   search.str threat.status notes
1 5744 Bixa arborea Huber          <NA> Bixaceae    species     accepted Bixa arborea            LC      
  original.search                                                  occurrence
1    Bixa arborea BR-AC|BR-AM|BR-BA|BR-ES|BR-MT|BR-PA|BR-RJ|BR-RO|BR-SP|BR-TO
```

But according [flora website](https://floradobrasil.jbrj.gov.br/FB5744), this is a species exclusive to the amazonic domain, not occurring in the Atlantic Forest (Bahia, Espírito Santo, Rio de Janeiro). Occurrences in the AF are actually the new species '[Bixa atlantica](https://floradobrasil.jbrj.gov.br/FB623453)' (not found using flora package). In the comments section on Bixa arborea we find:

`Bixa arborea Huber foi um nome largamente utilizado para identificar indivíduos arbóreos do gênero, de grande porte, que ocorrem na Mata Atlântica. Estudo recente detectou que essas identificações eram imprecisas, descrevendo uma nova espécie, Bixa atlantica Antar & Sano, para o domínio (Antar et al. 2022). As espécies podem ser facilmente diferenciadas já que Bixa arborea possui frutos inermes, enquanto B. atlantica possui frutos com espinhos. `

**Comment by gustavobio** [comment]
Probably not. Nowadays I only update this package to fix breaking bugs. If you clone the repo you will find all scripts needed to download and update the dataset. Anyway, I have updated the data and this is what I see now:

```{r}
get.taxa('Bixa arborea',states = TRUE)
    id    scientific.name accepted.name   family taxon.rank taxon.status   search.str threat.status.cnc threat.status.mma threat.status.mma2022 notes original.search
1 5744 Bixa arborea Huber          <NA> Bixaceae    species     accepted Bixa arborea                LC              <NA>                  <NA>          Bixa arborea
                           occurrence
1 BR-AC|BR-AM|BR-MT|BR-PA|BR-RO|BR-TO

get.taxa('Bixa atlantica',states = TRUE)
      id              scientific.name accepted.name   family taxon.rank taxon.status     search.str threat.status.cnc threat.status.mma threat.status.mma2022 notes
1 623453 Bixa atlantica  Antar & Sano          <NA> Bixaceae    species     accepted Bixa atlantica              <NA>              <NA>                  <NA>      
  original.search        occurrence
1  Bixa atlantica BR-BA|BR-ES|BR-MG
```

**Comment by jaum20** [comment]
@gustavobio can you please provide the command you used to update the database?
