### ISSUE TITLE
information not retrieved

### ISSUE THREAD

**Issue by MarioJose** [gustavobio/flora#5]
Dear Gustavo, 
I'm trying get life form information from some species, but get.taxa do not return it even that it is in Flora data base. For instance, Mimosa pigra on Flora has shrub as life form. But when I try retry this information with get.taxa, it return NA.

```r
get.taxa('Mimosa pigra',life.form = TRUE)
```
```
     id scientific.name accepted.name   family taxon.rank taxon.status   search.str
1 23088 Mimosa pigra L.          <NA> Fabaceae    species     accepted Mimosa pigra
  threat.status notes original.search life.form
1          <NA>          Mimosa pigra      <NA>
```
All the best,
Mario

**Comment by gustavobio** [comment]
Oi @MarioJose, o problema é que pra algumas espécies o banco da Flora do Brasil não está completamente atualizado:

```coffee
data(plants)
get.taxa(plants[1:3], life.form = T)
      id                                      scientific.name accepted.name        family taxon.rank taxon.status                    search.str
1 101410                Banisteriopsis paraguariensis B.Gates          <NA> Malpighiaceae    species     accepted Banisteriopsis paraguariensis
2  27864 Chamaecrista caespitosa (Benth.) H.S.Irwin & Barneby          <NA>      Fabaceae    species     accepted       Chamaecrista caespitosa
3 130389         Actinocephalus bahiensis (Bong.) F. N. Costa          <NA> Eriocaulaceae    species     accepted      Actinocephalus bahiensis
  threat.status            notes               original.search  life.form
1          <NA>                  Banisteriopsis paraguariensis    Arbusto
2          <NA> replaced synonym             Cassia caespitosa Subarbusto
3          <NA> replaced synonym           Eriocaulon bahiense       Erva
```

Não tem o que fazer enquanto isso não aparecer no banco que eles disponibilizam. Chequei na versão dessa semana e a espécie que você utilizou no exemplo ainda não aparece no banco. De qualquer forma, eu fiz uma função pra baixar isso da internet, é só passar a lista que sai da `get.taxa()`:

```coffee
> get_lifeform(get.taxa("Mimosa pigra"))
     id scientific.name accepted.name   family taxon.rank taxon.status   search.str
1 23088 Mimosa pigra L.          <NA> Fabaceae    species     accepted Mimosa pigra
  threat.status notes original.search life.form
1          <NA>          Mimosa pigra   Arbusto
```
Instale novamente pelo github pra ter acesso à ela, por favor.

**Comment by MarioJose** [comment]
Oi, @gustavobio.
Obrigado pela resposta! Já instalei a versão do Github. Por hora está voltando o erro "HTTP error 503" ao tentar usar a função.
```r
get_lifeform(get.taxa('Mimosa pigra'))
```
```
Error in open.connection(con, "rb") : HTTP error 503.
```
Acho que o servidor está com alguma instabilidade. Tentarei mais tarde.
Obrigado novamente!
Abraço,
Mario

**Comment by gustavobio** [comment]
Sim, tem uma mensagem no site http://floradobrasil.jbrj.gov.br/reflora/listaBrasil/:

"Prezados Pesquisadores,

O sistema está sendo atualizado.

Acesse novamente mais tarde.

Contamos com sua compreensão.

Coordenação da Lista de Espécies da Flora do Brasil"
