### ISSUE TITLE
instalando o pacote

### ISSUE THREAD

**Issue by avrodrigues** [gustavobio/flora#6]
olá Gustavo, estou tentando instalar o pacote como mostra o README, mas estou tendo problemas. 

A mensagem que aparece é:
Installing flora
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/avrodrigues/AppData/Local/Temp/Rtmpee84JM/devtools1e1c3dfa5757/gustavobio-flora-04dff91"  \
  --library="C:/Users/avrodrigues/Documents/R/win-library/3.4" --install-tests 

In R CMD INSTALL
Installation failed: Command failed (65535)
--------------------------------------------------------------------------------------------------------
Segue as informações da seção:

Session info -------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, mingw32             
 ui       RStudio (1.1.442)           
 language (EN)                        
 collate  Portuguese_Brazil.1252      
 tz       America/Sao_Paulo           
 date     2018-04-10                  

Packages -----------------------------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.4   2018-03-15 local         
 compiler    3.4.4   2018-03-15 local         
 curl        3.2     2018-03-28 CRAN (R 3.4.4)
 datasets  * 3.4.4   2018-03-15 local         
 devtools  * 1.13.5  2018-02-18 CRAN (R 3.4.3)
 digest      0.6.15  2018-01-28 CRAN (R 3.4.3)
 git2r       0.21.0  2018-01-04 CRAN (R 3.4.4)
 graphics  * 3.4.4   2018-03-15 local         
 grDevices * 3.4.4   2018-03-15 local         
 httr        1.3.1   2017-08-20 CRAN (R 3.4.4)
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.4)
 methods   * 3.4.4   2018-03-15 local         
 R6          2.2.2   2017-06-17 CRAN (R 3.4.4)
 stats     * 3.4.4   2018-03-15 local         
 tools       3.4.4   2018-03-15 local         
 utils     * 3.4.4   2018-03-15 local         
 withr       2.1.2   2018-03-15 CRAN (R 3.4.4)

**Comment by gustavobio** [comment]
Olá, só com esse log não sei o que pode ser. A versão do CRAN roda?

**Comment by avrodrigues** [comment]
oi gustavo, 

sim a versão CRAN roda, não sabia que já tinha ela. achei que era possivel instalar somente via github. 
problema solucionado. Obrigado pela atenção.

**Comment by gustavobio** [comment]
Opa, tranquilo. O pacote tem uns 4 anos de CRAN já. A versão aqui do github é levemente mais atual, mas tirando uma ou duas funções experimentais, tudo que tem lá tem aqui. No seu caso, provavelmente houve erro na instalação de algum pacote, mas nos logs o nome do pacote não veio. Abraços, Gustavo.,
