### ISSUE TITLE
Problems with the function get.synonyms

### ISSUE THREAD

**Issue by LimaRAF** [gustavobio/flora#7]
Oi Gustavo,

Primeiramente, parabéns pelo pacote, sou um usuário há anos e ele ajuda muita em minha pesquisa! Obrigado!

Há um tempo notei que a função 'get.synonyms' não me retornava os sinônimos, apenas um NULL. Resolvi olhar o código da função para ver onde estava o problema e tenho duas sugestões que podem ajudar a resolver:
- ao rodar o códiga da função "fora da função", linha por linha, eu substitui os objetos 'relationships' e 'all.taxa' por 'flora:::relationships' e 'flora:::all.taxa'. Mas, creio que isso talvez não seja necessário, dentro da função.
- ao olhar a coluna 'relationship' do objeto 'relationships', vi que a um problema de encoding. A expressão de busca que vc usa ('É sinônimo') está como "ÃƒÂƒÃ¢Â€Â° sinÃƒÂƒÃ‚Â´nimo". Não sei se é uma problema na minha máquina ou no arquivo fonte da FB. Mas, talvez valha a pena incluir uma linha o encoding check ou mais expressões regulares de busca no 'grepl'?

Novamente, parabéns pelo pacote. 

Renato

**Comment by gustavobio** [comment]
Oi, Renato, tudo bem? Eu acho que arquivo de onde vem esse relationships é setado com encoding errado duas vezes antes deles disponibilizarem. Depois eu dou uma olhada melhor nele, mas por enquanto resolvi de outra forma. Não lembro o motivo dessa busca com o grepl, então tirei isso por enquanto. Esses arquivos mudaram ao longo do tempo e isso pode ter ficado lá de forma residual.

Valeu pelo toque!
