### ISSUE TITLE
get.synonyms() not working

### ISSUE THREAD

**Issue by saramortara** [gustavobio/flora#9]
Olá Gustavo, 

Parece que a função `get.synonyms()` não está funcionando (estou com a versão 0.3.3). Por exemplo:

```
flora::get.synonyms("Myrcia splendens") 
```
retorna NULL

E o exemplo no help está `synonyms("Myrcia lingua")`

Porém, checando diretamente na API, tem 118 sinônimos: 

```
api <- "http://servicos.jbrj.gov.br/flora/taxon/"
res <- jsonlite::fromJSON(paste0(api, "Myrcia%20splendens"))
if (!is.null(res$result$SINONIMO)) {
sin.df <- res$result$SINONIMO[[1]]
  }
# so os nomes
sin.df$scientificname
```

**Comment by gustavobio** [comment]
Oi, Sara. Aqui funciona e a função retorna os 118 nomes do seu exemplo:

```r
require(dplyr)
api <- "http://servicos.jbrj.gov.br/flora/taxon/"
res <- fromJSON(paste0(api, URLencode("Myrcia splendens")))
res <- select(res$result$SINONIMO[[1]], scientificname, scientificnameauthorship)
res <- res %>%
  mutate(search.str = sapply(scientificname, remove.authors))
all(res$search.str %in% get.synonyms("Myrcia splendens"))
[1] TRUE

> packageVersion("flora")
[1] ‘0.3.3’
```

Eu vou subir uma versão nova agora pra corrigir outras coisas, mas tente reinstalar, por favor.

**Comment by Geiziane** [comment]
Oi Gustavo, 
Estou tendo o mesmo problema.
A função get.synonyms está retornando NA.
Por exemplo para "Commelina communis", que no site têm vários sinônimos.
get.synonyms("Commelina communis",
                             fix = T,
                             relationship = T)

Obrigada.

**Comment by gustavobio** [comment]
Olá @Geiziane 

A função está funcionando. No caso do taxon "Commelina communis", nos dados que a Flora do Brasil distribui não tem nenhuma espécie aceita com esse nome. Mesmo esta não aparece nos dados como aceita: https://floradobrasil.jbrj.gov.br/consulta/ficha.html?idDadosListaBrasil=127764

Não sei se por conta do "Não ocorre no Brasil" ali na página ou por ser algo recente e os dados que eles distribuem ainda não estarem atualizados.

A função `get.taxa()` sugere uma resolução manual (coluna notes):

```{R}
> get.taxa("Commelina communis")
  id scientific.name accepted.name family taxon.rank taxon.status search.str threat.status.cnc threat.status.mma threat.status.mma2022             notes    original.search
1 NA              NA            NA     NA         NA           NA         NA                NA                NA                    NA check +1 accepted Commelina communis
> get.taxa("Commelina communis", replace.synonyms = F)
  id scientific.name accepted.name family taxon.rank taxon.status search.str threat.status.cnc threat.status.mma threat.status.mma2022            notes    original.search
1 NA              NA            NA     NA         NA           NA         NA                NA                NA                    NA check +1 entries Commelina communis
```

**Comment by Geiziane** [comment]
Oi Gustavo,
Vou te explicar o que eu etou tetnando fazer e talvez vc tenha uma outra opção.

Estou uscando nomes para ver se sao aceitos ou sinonimos. Quando são sinonimos eu preciso saber a relação (se é homotípico, heterotipico).
Buscando por exemplo o nome "Disecocarpus polygamus" com a função get.taxa. a resultado retorna que e um sinonimo e retorna o nome aceito (que no caso é o Commelina communis L.) . Então eu busco os sinônimos do nome aceito para encontrar a relaçao.
As funçoes fazem busca em bases de dados diferentes? Pq na get.taxa "Commelina communis L." retorna como nome aceito, mas  get.synonyms, não encontra.

get.taxa("Disecocarpus polygamus",  replace.synonyms = F)

id                      scientific.name         accepted.name        family
1 127777 Disecocarpus polygamus (Roth) Hassk. Commelina communis L. Commelinaceae
taxon.rank taxon.status             search.str threat.status.cnc threat.status.mma
1    species      synonym Disecocarpus polygamus              <NA>              <NA>
  threat.status.mma2022 notes        original.search
1                  <NA>       Disecocarpus polygamus 

get.synonyms("Commelina communis ",
               fix = T,
               relationship = T)
NA


Obrigada!

**Comment by gustavobio** [comment]
Oi @Geiziane. `get.taxa` e `get.synonyms` usam dados empacotados em um mesmo dump, mas em arquivos diferentes. O problema não é esse.

![CleanShot 2023-10-26 at 17 50 41@2x](https://github.com/gustavobio/flora/assets/30267/9dd39b93-0d52-4f0f-9895-294fdaf2ed51)

Acima um screenshot do taxon.txt que a Flora distribui. Veja que Commelina communis L. aparece como nome aceito de várias espécies, mas não há nenhuma entrada para ela na coluna id.

Um outro exemplo (Myrcia guianensis):

![CleanShot 2023-10-26 at 17 56 25@2x](https://github.com/gustavobio/flora/assets/30267/37093065-88f2-4bac-a62d-48fd2b935637)

Ela aparece como uma entrada no banco (coluna ID) e como nome aceito de várias outras espécies.

![CleanShot 2023-10-26 at 17 57 44@2x](https://github.com/gustavobio/flora/assets/30267/e175ffd3-944e-4915-bf61-0cf19fd0a5ae)

Como a Commelina communis L. não aparece no arquivo de taxon, que é de onde as funções `get.synonyms` e `get.taxa` pegam o id de um taxon, os sinônimos dela não são listados.

Até daria para fazer uma segunda busca no código para pegar o id pelo AcceptedNameUsageID, mas isso parece mais erro do banco. Se você souber os ids pode pegar direto nos dados:

```
flora:::relationships %>% filter(related.id == 127764)
       id related.id            relationship
1  127775     127764 É sinônimo HETEROTIPICO
2  127768     127764 É sinônimo HETEROTIPICO
3  127773     127764 É sinônimo HETEROTIPICO
4  127771     127764 É sinônimo HETEROTIPICO
5  127769     127764 É sinônimo HETEROTIPICO
6  127767     127764 É sinônimo HETEROTIPICO
7  127770     127764 É sinônimo HETEROTIPICO
8  127774     127764 É sinônimo HETEROTIPICO
9  127772     127764 É sinônimo HETEROTIPICO
10 127777     127764 É sinônimo HETEROTIPICO
```

**Comment by gustavobio** [comment]
@Geiziane Só para complementar, eu testei umas 10 espécies com o mesmo problema e todas aparecem como "Não ocorre no Brasil" no site da Flora. Acho que na hora de construir o banco para distribuir eles tiram esses nomes.

https://floradobrasil.jbrj.gov.br/consulta/ficha.html?idDadosListaBrasil=618802

Como eu havia sugerido anteriormente, é o mesmo caso da Commelina communis L.:

https://floradobrasil.jbrj.gov.br/consulta/ficha.html?idDadosListaBrasil=127764

**Comment by Geiziane** [comment]
Oi Gustavo, realmente todas as espécies que testei aqui com esse problema, não ocorrem no Brasil.
Mas consegui resolver o problema com suas dicas.
Ao buscar pelo sinônimo, consigo o id do sinônimo e busco a relação dele.
Por ex:
> get.taxa("Brachymenium globosum",  replace.synonyms = F)
      id                scientific.name                            accepted.name
1 95973 Brachymenium globosum A.Jaeger Brachymenium columbicum (De Not.) Broth.
    family taxon.rank taxon.status            search.str threat.status.cnc
1 Bryaceae    species      synonym Brachymenium globosum              <NA>
  threat.status.mma threat.status.mma2022 notes       original.search
1              <NA>                  <NA>       Brachymenium globosum 

flora:::relationships %>% filter(id == 95973)
> flora:::relationships %>% filter(id == 95973)
     id related.id            relationship
1 95973      95969 É sinônimo HETEROTIPICO

Muitíssimo obrigada!
